# dbt/profiles.yml

projeto_dbt: # Este nome deve ser o mesmo que está em 'profile:' no seu dbt_project.yml
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'dbpg') }}" # Padrão: 'dbpg'
      user: "{{ env_var('DB_USER', 'user') }}" # Padrão: 'user'
      password: "{{ env_var('DB_PASSWORD', 'password') }}" # Padrão: 'password'
      port: 5432 # A porta é sempre 5432 dentro da rede do Docker
      dbname: "{{ env_var('DB_NAME', 'mydatabase') }}" # Padrão: 'mydatabase'
      schema: "{{ env_var('DB_SCHEMA', 'public') }}" # Padrão: 'public'
      threads: 4